name: Deploy Food solutions Project

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH and Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/my-app # اتأكد إن ده نفس اسم فولدر مشروعك على السيرفر
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # لو بتستخدم Laravel 11 وما فوق ممكن تحتاج الأمر ده
            # php artisan optimize 
            systemctl restart php-fpm
